// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hgrecap_metropolis
List rcpp_hgrecap_metropolis(IntegerVector n_drawn, IntegerVector K_marked, IntegerVector d_unmarked, int N_min, List prior, List control);
RcppExport SEXP hgrecap_rcpp_hgrecap_metropolis(SEXP n_drawnSEXP, SEXP K_markedSEXP, SEXP d_unmarkedSEXP, SEXP N_minSEXP, SEXP priorSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type n_drawn(n_drawnSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type K_marked(K_markedSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_unmarked(d_unmarkedSEXP);
    Rcpp::traits::input_parameter< int >::type N_min(N_minSEXP);
    Rcpp::traits::input_parameter< List >::type prior(priorSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    __result = Rcpp::wrap(rcpp_hgrecap_metropolis(n_drawn, K_marked, d_unmarked, N_min, prior, control));
    return __result;
END_RCPP
}
