# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hgrecap_metropolis <- function(n_drawn, K_marked, d_unmarked, N_min, prior, control) {
    .Call('hgrecap_rcpp_hgrecap_metropolis', PACKAGE = 'hgrecap', n_drawn, K_marked, d_unmarked, N_min, prior, control)
}

